# See https://wiki.debian.org/RaspberryPi3 for known issues and more details.

steps:
  - mkimg: "{{ output }}"
    size: 1500M

  - mklabel: msdos
    device: "{{ output }}"

  - mkpart: primary
    device: "{{ output }}"
    start: 0%
    end: 100%
    tag: /

  - kpartx: "{{ output }}"

  - mkfs: ext4
    partition: /
    label: ROOT

  - mount: /

  - unpack-rootfs: /

  - qemu-debootstrap: bullseye
    mirror: http://deb.debian.org/debian
    target: /
    arch: amd64
    components:
    - main
    - contrib
    - non-free
    unless: rootfs_unpacked

  - copy-file: /etc/initramfs-tools/hooks/rpi-resizerootfs
    src: rootfs/etc/initramfs-tools/hooks/rpi-resizerootfs
    perm: 0755
    unless: rootfs_unpacked

  - copy-file: /etc/initramfs-tools/scripts/local-bottom/rpi-resizerootfs
    src: rootfs/etc/initramfs-tools/scripts/local-bottom/rpi-resizerootfs
    perm: 0755
    unless: rootfs_unpacked

  - copy-file: /etc/apt/sources.list
    src: rootfs/etc/apt/sources.list
    perm: 0755
    unless: rootfs_unpacked

  - chroot: /
    shell: apt-get update
    unless: rootfs_unpacked

  - apt: install
    packages:
    - ssh
    - parted
    - dosfstools
    - iw
    - wpasupplicant
    - gnupg
    - curl
    - linux-image-amd64
    - grub-pc
    tag: /
    unless: rootfs_unpacked

  # Install variocube packages

  - copy-file: /etc/apt/sources.list.d/variocube.list
    src: rootfs/etc/apt/sources.list.d/variocube.list
    perm: 0755
    unless: rootfs_unpacked

  - chroot: /
    shell: curl https://og-repository.s3.amazonaws.com/debian/key.asc | apt-key add -
    unless: rootfs_unpacked

  - apt: install
    packages:
      - variocube-base
      - variocube-unit
    tag: /
    unless: rootfs_unpacked

  # Cache rootfs
  - cache-rootfs: /
    unless: rootfs_unpacked

  - fstab: /

  - shell: |
      echo "vc-image" > "${ROOT?}/etc/hostname"

      # Allow root logins locally with no password
      sed -i 's,root:[^:]*:,root::,' "${ROOT?}/etc/shadow"

      install -m 644 -o root -g root rootfs/etc/network/interfaces.d/eth0 "${ROOT?}/etc/network/interfaces.d/eth0"
      install -m 600 -o root -g root rootfs/etc/network/interfaces.d/wlan0 "${ROOT?}/etc/network/interfaces.d/wlan0"

      mkdir -p "${ROOT?}/etc/systemd/system/basic.target.requires/"
      mkdir -p "${ROOT?}/etc/systemd/system/multi-user.target.requires/"

      install -m 644 -o root -g root rootfs/etc/systemd/system/rpi-generate-ssh-host-keys.service "${ROOT?}/etc/systemd/system/"
      ln -s /etc/systemd/system/rpi-generate-ssh-host-keys.service "${ROOT?}/etc/systemd/system/multi-user.target.requires/rpi-generate-ssh-host-keys.service"
      rm -f "${ROOT?}"/etc/ssh/ssh_host_*_key*

      # Configure grub
      echo "GRUB_DISABLE_LINUX_UUID=true" >>"${ROOT?}/etc/default/grub"
      echo "GRUB_DISABLE_LINUX_PARTUUID=false" >>"${ROOT?}/etc/default/grub"
      echo "GRUB_DISABLE_OS_PROBER=true" >>"${ROOT?}/etc/default/grub"

    root-fs: /

  - grub: bios
    tag: /
    quiet: false
    device: "{{ output }}"

  # Clean up archive cache (likely not useful) and lists (likely outdated) to
  # reduce image size by several hundred megabytes.
  - chroot: /
    shell: |
      apt-get clean
      rm -rf /var/lib/apt/lists

  # TODO(https://github.com/larswirzenius/vmdb2/issues/24): remove once vmdb
  # clears /etc/resolv.conf on its own.
  - shell: |
      rm "${ROOT?}/etc/resolv.conf"
    root-fs: /

