#!/bin/sh
set -e

#
# List the soft prerequisites here.  This is a space separated list of
# names, of scripts that are in the same directory as this one, that
# must be run before this one can be.
#
PREREQS=""
case $1 in
    prereqs) echo "$PREREQS"; exit 0;;
esac

. /usr/share/initramfs-tools/hook-functions

copy_exec /usr/bin/realpath
copy_exec /usr/bin/tail
copy_exec /usr/bin/grep
copy_exec /usr/bin/lsblk
copy_exec /usr/sbin/blkid
copy_exec /usr/sbin/sfdisk
copy_exec /usr/sbin/partprobe
copy_exec /usr/sbin/resize2fs
copy_exec /usr/sbin/fsck
copy_exec /usr/sbin/e2fsck
