#!/usr/bin/env bash

usage() {
  echo "Usage: $0 <ROOT_DIR> <ARCH> <FILES> [PACKAGES...]"
  echo "  ROOT_DIR    Directory to bootstrap the system into."
  echo "  ARCH        Architecture to install: amd64, armhf, arm64, ..."
  echo "  FILES       Comma-separated list of file trees to copy (from src/rootfs)"
  echo "  PACKAGES    Additional packages to install"
  exit 1
}

ROOT_DIR=$1
ARCH=$2
FILES=$3

shift 3

if [[ ! -d "$ROOT_DIR" ]]; then
  echo "ROOT_DIR not specified, or directory does not exist."
  usage
fi

if [[ -z "$ARCH" ]]; then
  echo "ARCH not specified."
  usage
fi

if [[ -z "$FILES" ]]; then
  echo "FILES not specified."
  usage
fi


set -e
set -x

for FILETREE in $(tr ',' '\n' <<< "$FILES")
do
  rsync -rptv "src/rootfs/$FILETREE/" "${ROOT_DIR}/"
done

# Bootstrap base system
debootstrap --arch "$ARCH" \
  --components main,contrib,non-free \
  --include ca-certificates \
  bullseye "$ROOT_DIR" http://deb.debian.org/debian

# Install packages
chroot "$ROOT_DIR" apt-get update
chroot "$ROOT_DIR" env DEBIAN_FRONTEND=noninteractive apt-get install \
  -o "Dpkg::Options::=--force-confdef" -o "Dpkg::Options::=--force-confold" --force-yes -y --no-install-recommends \
    systemd-sysv console-setup locales sudo dbus-user-session bsdmainutils \
    ssh netcat iproute2 iputils-ping \
    usbutils lshw \
    parted dosfstools gdisk \
    python3 \
    vim less gnupg curl htop \
    variocube-unit variocube-app-host variocube-kiosk \
    "$@" # additional packages supplied as arguments

# Remove hostname it is generated by `genhostname` in initramfs
rm -f ${ROOT_DIR?}/etc/hostname

# Clear SSH host keys and enable our service that regenerates them on first boot
rm -f ${ROOT_DIR?}/etc/ssh/ssh_host_*_key*
mkdir -p ${ROOT_DIR?}/etc/systemd/system/multi-user.target.requires
ln -s ${ROOT_DIR?}/etc/systemd/system/generate-ssh-host-keys.service ${ROOT_DIR?}/etc/systemd/system/multi-user.target.requires/generate-ssh-host-keys.service

# Print df here, because that's the max space we need
df

# Clean up archive cache (likely not useful) and lists (likely outdated) to
# reduce image size by several hundred megabytes.
chroot "$ROOT_DIR" apt-get clean
chroot "$ROOT_DIR" rm -rf /var/lib/apt/lists

# Clear /etc/machine-id, as it should be auto-generated upon first boot.
# Note this will also trigger ConditionFirstBoot=yes for systemd.
chroot "$ROOT_DIR" truncate -s0 /etc/machine-id
