name: release
on: [release, push]

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
    - uses: actions/checkout@v2
    - uses: docker/setup-qemu-action@v1
    - run: ./build.sh
    # TODO: Compress and upload
    # - run: ./compress.sh

