name: release
on:
  push:
    tags: ["*"]

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
    - uses: actions/checkout@v2
    - run: |
        sudo apt-get update
        sudo apt-get install --no-install-recommends -y \
          dosfstools qemu-utils qemu-user-static debootstrap binfmt-support time \
          parted kpartx rsync curl
    - run: sudo ./build.sh
    - run: sudo ./compress.sh
    - name: Release
      uses: softprops/action-gh-release@v1
      with:
        files: ./build/*.xz