name: release
on: [release, push]

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
    - uses: actions/checkout@v2
    - run: |
        apt-get update
        apt-get install --no-install-recommends -y \
          dosfstools qemu-utils qemu-user-static debootstrap binfmt-support time \
          parted kpartx rsync curl
    - run: ./build.sh
    # TODO: Compress and upload
    # - run: ./compress.sh

